models/User.php
<?php

namespace app\models;


use app\helpers\SQL;
use app\traits\BroadcastModelTrait;
use Yii;
use yii\db\ActiveRecord;

/**
 * Class User
 * @property boolean $admin
 * @property integer $id
 * @property integer $parent
 * @property string $nick
 * @property string $type
 * @property string $surname
 * @property string $forename
 * @property string $email
 * @property string $skype
 * @property string $secret
 * @property string $password
 * @property string $phone
 * @property string $country
 * @property string $settlement
 * @property string $address
 * @property string $blockio
 * @property string $ethereum
 * @package app\models
 */
class User extends ActiveRecord
{
    use BroadcastModelTrait;

    public $password;
    public $sponsor;
    public $level;
    public $ip;
    public $avatar_file;

    public static function tableName() {
        return 'user';
    }

    public function rules() {
        return [
            ['id', 'integer'],
            [['nick', 'email'], 'required'],
            [['surname', 'forename'], 'string', 'min' => 2, 'max' => 48],
            ['nick', 'string', 'min' => 4, 'max' => 24],
            ['nick', 'match', 'pattern' => '/^[a-z][a-z0-9_]+$/i'],
            ['email', 'email'],
            ['ip', 'ip'],
            [['ethereum', 'telegram'], 'string'],
            ['perfect', 'match', 'pattern' => '/^U\d{7,8}$/', 'message' => 'Format must be U1234567'],
            ['skype', 'match', 'pattern' => '/^[a-zA-Z][a-zA-Z0-9\.,\-_]{5,31}$/'],
            [['surname', 'forename', 'nick', 'email', 'skype', 'perfect', 'sponsor', 'password', 'phone',
                'country', 'settlement', 'address', 'avatar', 'telegram'], 'filter', 'filter' => 'trim'],
            [['surname', 'forename', 'nick', 'email', 'skype', 'perfect', 'sponsor', 'password', 'phone',
                'country', 'settlement', 'address', 'avatar', 'telegram'], 'filter', 'filter' => 'strip_tags'],
            [['surname', 'forename', 'nick', 'email', 'skype', 'perfect', 'sponsor', 'password', 'phone',
                'country', 'settlement', 'address', 'avatar', 'telegram'], 'filter', 'filter' => function ($s) {
                return $s ?: null;
            }],
            [['nick', 'email', 'skype', 'perfect'], 'unique',
                'targetClass' => 'app\models\User',
                'message' => Yii::t('app', 'This value has already been taken')],
            ['sponsor', 'exist',
//                'targetClass' => 'app\models\User',
                'targetAttribute' => 'nick',
                'message' => Yii::t('app', 'Sponsor not found')],
        ];
    }

    public function attributeLabels() {
        return [
            'address' => Yii::t('app', 'Address'),
            'avatar_file' => Yii::t('app', 'Avatar'),
            'country' => Yii::t('app', 'Country'),
            'email' => Yii::t('app', 'Email'),
            'forename' => Yii::t('app', 'First Name'),
            'nick' => Yii::t('app', 'Username'),
            'password' => Yii::t('app', 'Password'),
            'perfect' => Yii::t('app', 'Perfect Money'),
            'phone' => Yii::t('app', 'Phone'),
            'telegram' => Yii::t('app', 'Telegram'),
            'settlement' => Yii::t('app', 'City'),
            'skype' => Yii::t('app', 'Skype'),
            'sponsor' => Yii::t('app', 'Sponsor'),
            'surname' => Yii::t('app', 'Last Name'),
        ];
    }

    /**
     * @param string $id
     * @return User
     */
    public static function findIdentity($id) {
        return parent::findOne(['id' => $id]);
    }

    public function validatePassword(string $password) {
        return password_verify($password, $this->secret);
    }

    public function generateAuthKey() {
        return $this->generateToken('browser', Yii::$app->security->generateRandomString(24));
    }

    public function generateCode() {
        return $this->generateToken('code', Yii::$app->security->generateRandomString(48));
    }

    public function generateSecret() {
        $this->secret = str_replace('$2y$', '$2a$', password_hash($this->password, PASSWORD_BCRYPT));
    }

    public static function getIdByNick($nick) {
        return static::find()
            ->where(['nick' => $nick])
            ->select(['id'])
            ->one()
            ->id;
    }

    public function generateToken(string $type, $id) {
        if (Yii::$app->db->createCommand()->insert('token', [
            'id' => $id,
            'type' => $type,
            'user' => $this->id,
        ])
            ->execute()
        ) {
            return $id;
        }
        return false;
    }

    public function isAdmin() {
        return $this->admin;
    }

    public function __toString() {
        return $this->nick;
    }

    public function sendEmail($template, $params) {
        $template = Yii::getAlias('@app') . "/mail/$template.php";
        return Yii::$app->mailer->compose()
            ->setTo($this->email)
            ->setFrom(['zbyszek@yopmail.com' => 'admin'])
            ->setSubject($params['subject'])
            ->setHtmlBody(Yii::$app->view->renderFile($template, $params))
            ->send();
    }

    public static function getBalance($currency, $id = null) {
        if (null === $id) {
            $id = Yii::$app->user->identity->user;
        }
        return SQL::scalar('SELECT amount FROM balance WHERE "user" = :id AND currency = :currency', [
            ':id' => $id,
            ':currency' => $currency,
        ]);
    }

    public function canLogin() {
        return true;
//        return Record::find()->andWhere([
//            'object_id' => $this->id,
//            'event' => 'login_fail'
//        ])
//            ->andWhere('time > DATE_SUB(NOW(), INTERVAL 5 MINUTE)')
//            ->count() < 10;
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\behaviors\Access;
use app\helpers\SQL;
use app\models\Email;
use app\models\form\Login;
use app\models\form\PasswordReset;
use app\models\form\RequestPasswordReset;
use app\models\form\Signup;
use app\models\Identity;
use app\models\Log;
use app\models\Token;
use app\models\Transfer;
use app\models\User;
use Yii;
use yii\db\Query;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\ForbiddenHttpException;
use yii\web\Response;

class UserController extends RestController
{
    public function behaviors() {
        return [
            'access' => [
                'class' => Access::class,
                'plain' => ['logout', 'profile'],
                'guest' => ['login', 'signup']
            ]
        ];
    }

    public function beforeAction($action) {
        if ('authorize' === $action->id) {
            Yii::$app->request->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }

    public function actionSignup() {
        $this->layout = '@app/views/layouts/outdoor';
        $model = new Signup();
        $sponsor = Yii::$app->request->get('sponsor');
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->parent = User::getIdByNick($model->sponsor ?: 'trader');
            $model->generateSecret();
            $model->save(false);
            Email::send($model->email, 'Welcome', "Dear, $model->nick \nThank you for registration at " . Yii::$app->name);
            $identity = Identity::identifyCookie();
            $identity->login($model->id);
            $o = $model->getAttributes(['nick', 'email', 'skype', 'sponsor']);
            if (!$model->sponsor && $sponsor) {
                $o['sponsor'] = $model->sponsor;
            }
            Log::log('user', 'signup', $o);
            Yii::$app->user->setIdentity($identity);
            return $this->redirect(['user/profile', 'nick' => $model->nick]);
        } else {
            $model->sponsor = $sponsor ?: 'trader';
        }
        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionLogin() {
        $this->layout = '@app/views/layouts/outdoor';
        $notCheck = !Yii::$app->params['checkLoginAttempt'];

        $model = new Login();
        if ($model->load(Yii::$app->request->post())) {
            $user = null;
            if ($notCheck || Login::checkLoginAttempt(['ip' => Yii::$app->request->getUserIP()])) {
                $user = $model->getUser();
                if ($user && ('special' !== $user->type || 'trader' === $user->nick)) {
                    if ('blocked' === $user->type) {
                        $model->addError('login', Yii::t('app', 'User is blocked'));
                    }
                    else if ($notCheck || Login::checkLoginAttempt(['user' => $user->id])) {
                        if ($user->validatePassword($model->password)) {
                            $identity = Identity::identifyCookie();
                            $identity->login($user->id);
                            Yii::$app->user->setIdentity($identity);
                            Log::log('auth', 'login', $model->getAttributes(['login', 'ip']));
                            return $this->redirect(['user/profile', 'nick' => $user->nick]);
                        } else {
                            $model->addError('password', Yii::t('app', 'Invalid password'));
                        }
                    }
                } else {
                    $model->addError('login', Yii::t('app', 'User does not exists'));
                }
            }
            Log::log('auth', 'invalid', $model->getAttributes(['login', 'ip']), $user ? $user->id : null);
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout() {
        Access::verifyNick();
        $id = Yii::$app->user->identity->user;
        Yii::$app->user->identity->logout(null);
        Yii::$app->user->setIdentity(null);
        Log::log('auth', 'logout', null, $id);
        return $this->redirect(['user/login']);
    }

    public function actionProfile($nick) {
        if ($nick !== Yii::$app->user->identity->nick) {
            throw new ForbiddenHttpException();
        }
        $informer = (new Query())
            ->from('informer')
            ->where(['nick' => $nick])
            ->one();
        $informer = array_merge($informer, Transfer::getFinance($informer['id']));

        if ($informer['parent']) {
            $informer['parent'] = json_decode($informer['parent']);
        }

        return $this->render('profile', ['model' => $informer]);
    }

    public function actionRequest() {
        $this->layout = '@app/views/layouts/outdoor';
        $model = new RequestPasswordReset();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if (($user = $model->getUser())
                && ($code = $user->generateCode())
                && (Email::send($user->email, Yii::t('app', 'Password Recovery'),
                    'You can recover your password ' . Url::to(['user/reset', 'code' => $code], true)))
            ) {
                Yii::$app->session->addFlash('success', Yii::t('app', 'Check your email'));
            } else {
                Yii::$app->session->addFlash('error', Yii::t('app', 'User not found'));
            }
        }
        return $this->render('request', ['model' => $model]);
    }

    public function actionReset($code) {
        $this->layout = '@app/views/layouts/outdoor';
        $model = new PasswordReset();
        $token = Token::findOne(['id' => $code]);
        if ($token) {
            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                $user = User::findOne(['id' => $token->user]);
                $user->password = $model->password;
                $user->generateSecret();
                if ($user->save(false) && $token->delete()) {
                    Yii::$app->session->addFlash('success', Yii::t('app', 'Password changed'));
                }
                Log::log('auth', 'password', ['code' => $code], $user->id);
                return $this->redirect(['user/login']);
            }
        } else {
            Yii::$app->session->addFlash('error', Yii::t('app', 'Password recovery code not found'));
            Log::log('auth', 'invalid', ['code' => $code]);
        }
        return $this->render('reset', ['model' => $model]);
    }

    public function actionAuthorize($nick) {
        if (empty($_REQUEST['token'])) {
            throw new BadRequestHttpException('Token not set');
        }
        $user = User::find()->where(['nick' => $nick])->select(['id', 'nick', 'admin'])->one();
        if ($user) {
            $isAdmin = SQL::scalar('SELECT count(*) FROM identity WHERE admin AND id = :id', ['id' => $_REQUEST['token']]) > 0;
            if ($isAdmin && !$user->admin) {
                Identity::identifyCookie()->login($user->id);
                Log::log('auth', 'token');
                return $this->redirect(['user/profile', 'nick' => $user->nick]);
            }
            throw new ForbiddenHttpException();
        }
        throw new BadRequestHttpException('User not found');
    }
/*
    public function actionContact($id) {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $contact = SQL::queryOne(
            'SELECT id, nick, email, skype, avatar, surname, forename FROM "user" WHERE ("type" <> \'special\' OR id > 1) AND id = :id', [
            ':id' => $id
        ]);
        if ($contact) {
            return ['result' => $contact];
        }
        Yii::$app->response->statusCode = 404;
        return ['status' => 404];
    }
*/
}

views/user/_card.php
<?php
/**
 * @var app\models\User $model
 */

use yii\helpers\Html;

?>

<div class="card">
    <div class="card-image waves-effect waves-block waves-light">
        <img class="activator" src="/images/user-bg.jpg" alt="user background">
    </div>
    <div class="card-content">
        <img src="<?= $model->avatar ?: '/images/user.png' ?>" alt="sponsot"
             class="circle responsive-img activator card-profile-image">
        <a class="btn-floating activator btn-move-up waves-effect waves-light darken-2 right">
            <i class="mdi-action-account-circle"></i>
        </a>
        <span class="card-title activator grey-text text-darken-4"><?= Html::encode($model->forename . ' ' . $model->surname) ?></span>
        <br>
        <span><?= Yii::t('app', 'Your Sponsor') ?></span>

        <p>
            <i class="mdi-action-perm-identity light-blue-text text-lighten-1"></i>
            <span><?= Html::encode($model->nick) ?></span>
        </p>

        <?php if (!empty($model->email)) {
            echo '<p><i class="mdi-communication-email light-blue-text text-lighten-1"></i><span> ' . $model->email . '</span> </p>';
        }
        ?>
        <?php if (!empty($model->skype)) {
            echo '<p><i class="fa fa-skype light-blue-text text-lighten-1"></i><span>' . $model->skype . '</span> </p>';
        }
        ?>
        <?php if (!empty($model->telegram)) {
            echo '<p><i class="fa fa-telegram light-blue-text text-lighten-1"></i><span>' . $model->telegram . '</span> </p>';
        }
        ?>
    </div>
    <div class="card-reveal">
                            <span class="card-title grey-text text-darken-4">
                                <?= Html::encode($model->forename . ' ' . $model->surname) ?>
                                <i class="mdi-navigation-close right"></i>
                            </span>
        <p><?= Yii::t('app', '{days} days at ICO Holding', ['days' => 15]) ?></p>
        <?php if (!empty($model->country)) {
            echo '<p><i class="mdi-social-public light-blue-text text-lighten-1"></i><span>' . $model->country . '</span> </p>';
        }
        ?>
        <?php if (!empty($model->settlement)) {
            echo '<p><i class="mdi-social-location-city light-blue-text text-lighten-1"></i><span>' . $model->settlement . '</span> </p>';
        }
        ?>
        <?php if (!empty($model->address)) {
            echo '<p><i class="mdi-action-account-balance light-blue-text text-lighten-1"></i><span>' . $model->address . '</span> </p>';
        }
        ?>
    </div>
</div>

views/user/login.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\form\Login */
/* @var $form ActiveForm */

$this->title = 'Login'
?>

<div id="login-page" class="row">
    <div class="col s12 z-depth-4 card-panel">
        <?php $form = ActiveForm::begin(['options' => ['class' => 'login-form']]); ?>
        <div class="row">
            <div class="input-field col s12 center">
                <img src="/images/login-logo.png" alt="ICO Holding Logo" class="responsive-img valign ">
                <p class="center login-form-text">
                    <?= Yii::t('app', '<strong>Login</strong><br> in back office') ?>
                </p>
            </div>
        </div>

        <?= $form->field($model, 'login', [
            'template' => '<div class="row margin">
          			<div class="input-field col s12">
            			<i class="mdi-social-person prefix"></i>{input}{label}{error}{hint}</div></div>'
        ])->textInput(['maxlength' => 24, 'id' => 'username', 'class' => ''])
        ?>

        <?= $form->field($model, 'password', [
            'template' => '<div class="row margin">
          			<div class="input-field col s12">
            			<i class="mdi-action-lock-outline prefix"></i>{input}{label}{error}{hint}</div></div>'
        ])->passwordInput(['maxlength' => 100, 'id' => 'password', 'class' => ''])
        ?>

        <?= $form->field($model, 'ip')->hiddenInput()->label(false) ?>

        <div class="row">
            <div class="input-field col s12">
                <?= Html::submitButton(Yii::t('app', 'Login'), ['class' => 'btn waves-effect red darken-2 col s12']) ?>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6 m6 l6">
                <p class="margin medium-small">
                    <?= Html::a(Yii::t('app', 'Register'), ['user/signup'], ['class' => 'red-text darken-2-text']) ?>
                </p>
            </div>
            <div class="input-field col s6 m6 l6">
                <p class="margin right-align medium-small">
                    <?= Html::a(Yii::t('app', 'Forgot Password?'), ['user/request'], ['class' => 'red-text darken-2-text']) ?>
                </p>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>


<!-- user-login -->

views/user/password.php
<?php

use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $message string
 * @var $model app\models\Password
 * @var $form ActiveForm
 */

$reset = !$model || 'reset' == $model->scenario;
$this->title = Yii::t("app", $reset ? 'Reset Password' : 'Set Password');
if (!$reset) {
    $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
    $this->params['breadcrumbs'][] = ['label' => $model->user_name, 'url' => ['view', 'name' => $model->user_name]];
    $this->params['breadcrumbs'][] = Yii::t('app', 'Password');
}

if ($message):
    echo "<div class=\"alert alert-danger\">$message</div>";
else:
    ?>
    <div class="user-password">
        <h1><?= $this->title ?></h1>
        <?php $form = ActiveForm::begin(); ?>

        <?php if (!$reset) {
            echo $form->field($model, 'password')->passwordInput();
        } ?>
        <?= $form->field($model, 'new_password')->passwordInput() ?>
        <?= $form->field($model, 'repeat_password')->passwordInput() ?>

        <?= $form->field($model, 'ip')->hiddenInput()->label(false) ?>

        <div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-primary']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
<?php
endif;

views/user/request.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $message string
 * @var $model app\models\form\RequestPasswordReset
 * @var $form ActiveForm
 */

$this->title = Yii::t('app', 'Password Recovery Request');

?>

<div id="login-page" class="password-recovery-request row">
    <div class="col s12 z-depth-4 card-panel">
        <?php $form = ActiveForm::begin(['options' => ['class' => 'login-form']]); ?>
        <form class="login-form">

            <div class="row">
                <div class="input-field col s12 center">
                    <img src="/images/login-logo.png" alt="" class="responsive-img valign">
                    <h4><?= Yii::t('app', 'Reset password') ?></h4>

                    <p class="center"><?=
                        Yii::t('app',
                            'Enter Email or login for reset password!') ?></p>
                </div>
            </div>

            <?=
            $form->field($model, 'email', [
                'template' => ' <div class="row margin">
          <div class="input-field col s12">
            <i class="mdi-social-person-outline prefix"></i>{input}{label}{error}{hint}</div></div>'
            ])->textInput(['maxlength' => 100, 'id' => 'email', 'class' => ''])
            ?>
            <?=
            $form->field($model, 'nick', [
                'template' => ' <div class="row margin">
          <div class="input-field col s12">
            <i class="mdi-social-person-outline prefix"></i>{input}{label}{error}{hint}</div></div>'
            ])->textInput(['maxlength' => 100, 'id' => 'nick', 'class' => ''])
            ?>

            <div class="row">
                <div class="input-field col s12">
                    <?= Html::submitButton(Yii::t('app', 'Send Email'), ['class' => 'btn waves-effect red darken-2 col s12']) ?>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s6 m6 l6">
                    <p class="margin medium-small">
                        <?= Html::a(Yii::t('app', 'Register'), ['user/signup'], ['class' => 'red-text darken-2-text']) ?>
                    </p>
                </div>
                <div class="input-field col s6 m6 l6">
                    <p class="margin right-align medium-small">
                        <?= Html::a(Yii::t('app', 'Forgot Password?'), ['user/request'], ['class' => 'red-text darken-2-text']) ?>
                    </p>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
    </div>
</div>

views/user/reset.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $message string
 * @var $model app\models\form\RequestPasswordReset
 * @var $form ActiveForm
 */

$this->title = Yii::t('app', 'Password Recovery');

?>



<div id="login-page" class="password-recovery row">
    <div class="col s12 z-depth-4 card-panel">
        <?php $form = ActiveForm::begin(['options' => ['class' => 'login-form']]); ?>
        <form class="login-form">

            <div class="row">
                <div class="input-field col s12 center">
                    <img src="/images/login-logo.png" alt="" class="responsive-img valign">
                    <h4><?= Yii::t('app', 'Reset password') ?></h4>

                    <p class="center"><?=
                        Yii::t('app',
                            'Enter new password!') ?></p>
                </div>
            </div>

            <?=
            $form->field($model, 'password', [
                'template' => ' <div class="row margin">
          <div class="input-field col s12">
            <i class="mdi-social-person-outline prefix"></i>{input}{label}{error}{hint}</div></div>'
            ])->passwordInput(['maxlength' => 100, 'id' => 'password', 'class' => ''])
            ?>
            <?=
            $form->field($model, 'repeat', [
                'template' => ' <div class="row margin">
          <div class="input-field col s12">
            <i class="mdi-social-person-outline prefix"></i>{input}{label}{error}{hint}</div></div>'
            ])->passwordInput(['maxlength' => 100, 'id' => 'repeat', 'class' => ''])
            ?>

            <?= $form->field($model, 'ip')->hiddenInput()->label(false) ?>

            <div class="row">
                <div class="input-field col s12">
                    <?= Html::submitButton(Yii::t('app', 'Reset'), ['class' => 'btn waves-effect red darken-2 col s12']) ?>
                </div>

            </div>
            <div class="row">
                <div class="input-field col s6 m6 l6">
                    <p class="margin medium-small">
                        <?= Html::a(Yii::t('app', 'Register'), ['user/signup'], ['class' => 'red-text darken-2-text']) ?>
                    </p>
                </div>
                <div class="input-field col s6 m6 l6">
                    <p class="margin right-align medium-small">
                        <?= Html::a(Yii::t('app', 'Forgot Password?'), ['user/request'], ['class' => 'red-text darken-2-text']) ?>
                    </p>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
    </div>
</div>

views/user/signup.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Registration'
?>

<div id="login-page" class="row">
    <div class="col s12 z-depth-4 card-panel">
        <?php $form = ActiveForm::begin(['options' => ['class' => 'login-form signup-form']]); ?>
        <div class="row">
            <div class="input-field col s12 center">
                <img src="/images/login-logo.png" alt="ICO Holding Logo" class="responsive-img valign">
                <h4><?= Yii::t('app', 'Create an account') ?></h4>
                <p class="center"><?= Yii::t('app',
                        'Join to the out community of successful investors now!') ?></p>
            </div>
        </div>

        <?= $form->field($model, 'nick', [
            'template' => ' <div class="row margin">
          <div class="input-field col s12">
            <i class="mdi-social-person-outline prefix"></i>{input}{label}{error}{hint}</div></div>'
        ])->textInput(['maxlength' => 24, 'id' => 'username', 'class' => ''])
        ?>

        <?= $form->field($model, 'email', [
            'template' => ' <div class="row margin">
          <div class="input-field col s12">
            <i class="mdi-communication-email prefix"></i>{input}{label}{error}{hint}</div></div>'
        ])->textInput(['maxlength' => 48, 'id' => 'email', 'class' => ''])
        ?>

        <?= $form->field($model, 'password', [
            'template' => '<div class="row margin">
                    <div class="input-field col s12">
                        <i class="mdi-action-lock-outline prefix"></i>{input}{label}{error}{hint}</div></div>'
        ])->passwordInput(['maxlength' => 100, 'id' => 'password', 'class' => '',
            'autocomplete' => 'off'])
        ?>
        <!--      <?= $form->field($model, 'skype', [
            'template' => ' <div class="row margin">
          <div class="input-field col s12">
            <i class="mdi-social-person-outline prefix"></i>{input}{label}{error}{hint}</div></div>'
        ])->textInput(['maxlength' => 48, 'id' => 'skype', 'class' => ''])
        ?>-->
        <?= $form->field($model, 'sponsor', [
            'template' => ' <div class="row margin">
          <div class="input-field col s12">
            <i class="mdi-social-person-outline prefix"></i>{input}{label}{error}{hint}</div></div>'
        ])->textInput(['maxlength' => 24, 'id' => 'username', 'class' => ''])
        ?>

        <?= $form->field($model, 'ip')->hiddenInput()->label(false) ?>

        <div class="row">
            <div class="input-field col s12">
                <?= Html::submitButton(Yii::t('app', 'Signup'), ['class' => 'btn waves-effect red darken-2 col s12']) ?>
            </div>
            <div class="input-field col s12">
                <p class="margin center medium-small sign-up">
                    <span><?= Yii::t('app', 'Have an account already?') ?></span>
                    <?= Html::a(Yii::t('app', 'Login'), ['user/login'], ['class' => 'red-text darken-2-text']) ?>
                </p>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>